# Generated by Django 5.2.8 on 2025-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_remove_bill_customer_name_bill_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque'), ('CARD', 'Card')], default='CASH', help_text='UPI/Cash/Online/Cheque/Card', max_length=20),
        ),
    ]
