# Generated by Django 5.2.8 on 2025-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendor_bill_customer_address_bill_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
