# Generated by Django 5.2.8 on 2025-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_module_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='shop_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gst_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
