# Generated by Django 5.2.8 on 2025-12-11 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_shop_name_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='student_employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='assisted_bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
