# Generated by Django 5.2.8 on 2025-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fix_db_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Regular Employee'), ('STUDENT', 'Student Employee')], max_length=20, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
