# Generated by Django 5.2.8 on 2025-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_inventorysession_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysession',
            name='remarks',
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='payment_details',
            field=models.TextField(blank=True, help_text='Transaction ID or other payment info'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='payment_type',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('NEFT', 'NEFT/IMPS')], default='CASH', max_length=20),
        ),
    ]
