# Generated by Django 5.2.8 on 2025-12-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_inventorysession_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysession',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='inventorysession',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='InventorySessionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('NEFT', 'NEFT/IMPS')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.inventorysession')),
            ],
        ),
    ]
