# Generated by Django 5.2.8 on 2025-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_inventorysession_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysession',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
