# Generated by Django 5.2.8 on 2026-01-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_inventorysession_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
