# Generated by Django 5.2.8 on 2026-01-05 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_account_holder_name_user_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='ordered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
