# Generated by Django 5.2.8 on 2026-01-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
