# Generated by Django 5.2.8 on 2026-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_purchaserecord_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('NEFT', 'NEFT/IMPS')], max_length=20, null=True),
        ),
    ]
