# Generated by Django 5.2.8 on 2026-03-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_account_holder_name_user_account_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentWorkLog',
        ),
    ]
