# Generated by Django 5.2.8 on 2026-03-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_studentworklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
