from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import invoice

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', redirect_authenticated_user=True), name='login_home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('users/', views.user_list, name='user_list'),
    path('users/create/', views.create_user, name='create_user'),
    path('users/<int:pk>/permissions/', views.manage_user_permissions, name='manage_user_permissions'),
    path('roles/', views.role_list, name='role_list'),
    path('roles/<str:role_code>/edit/', views.edit_role_permissions, name='edit_role_permissions'),
    path('items/', views.item_list, name='item_list'),
    path('items/create/', views.create_item, name='create_item'),
    path('items/edit/<int:pk>/', views.edit_item, name='edit_item'),
    path('items/delete/<int:pk>/', views.delete_item, name='delete_item'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/create/', views.create_customer, name='create_customer'),
    path('customers/edit/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('customers/delete/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('billing/', views.billing_home, name='billing_home'),
    path('bill/create/inner/', views.create_bill, {'bill_type': 'INNER'}, name='create_bill_inner'),
    path('bill/create/outer/', views.create_bill, {'bill_type': 'OUTER'}, name='create_bill_outer'),
    path('bill/create/sales/', views.create_bill, {'bill_type': 'SALES'}, name='create_bill_sales'),
    path('bill/create/<str:bill_type>/', views.create_bill, name='create_bill'),
    path('bill/<int:pk>/', views.bill_detail, name='bill_detail'),
    path('bills/', views.bill_list, name='bill_list'),
    path('bill/edit/<int:pk>/', views.edit_bill, name='edit_bill'),
    path('bill/delete/<int:pk>/', views.delete_bill, name='delete_bill'),
    path('profile/', views.profile, name='profile'),
    path('bills/export/', views.export_bills, name='export_bills'),
    path('invoice/', invoice.invoice_list, name='invoice_list'),
    path('invoice/export/', invoice.invoice_export, name='invoice_export'),
    path('inventory/', views.inventory_list, name='inventory_list'),
    path('inventory/create/', views.create_inventory_session, name='create_inventory_session'),
    path('inventory/edit/<int:pk>/', views.edit_inventory_session, name='edit_inventory_session'),
    path('inventory/close/<int:pk>/', views.close_inventory_session, name='close_inventory_session'),
    path('vendors/', views.vendor_list, name='vendor_list'),
    path('vendors/export/', views.export_vendors, name='export_vendors'),
    path('vendors/create/', views.create_vendor, name='create_vendor'),
    path('vendors/edit/<int:pk>/', views.edit_vendor, name='edit_vendor'),
    path('vendors/delete/<int:pk>/', views.delete_vendor, name='delete_vendor'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/edit/<int:pk>/', views.edit_employee, name='edit_employee'),
    path('employees/delete/<int:pk>/', views.delete_employee, name='delete_employee'),
    path('attendance/', views.attendance_list, name='attendance_list'),
    path('attendance/create/', views.create_attendance, name='create_attendance'),
    path('attendance/clock-in/', views.clock_in, name='clock_in'),
    path('attendance/clock-out/', views.clock_out, name='clock_out'),
    path('attendance/approve/', views.approve_attendance, name='approve_attendance'),
    path('worklogs/', views.worklog_list, name='worklog_list'),
    path('worklogs/start/', views.start_worklog, name='start_worklog'),
    path('worklogs/end/', views.end_worklog, name='end_worklog'),
    path('worklogs/approve/<int:pk>/', views.approve_worklog, name='approve_worklog'),
    path('purchases/', views.purchase_list, name='purchase_list'),
    path('purchases/export/', views.export_purchases, name='export_purchases'),
    path('purchases/export/pending/', views.export_pending_purchases, name='export_pending_purchases'),
    path('purchases/create/', views.create_purchase, name='create_purchase'),
    path('vendor-payments/', views.vendor_payment_list, name='vendor_payment_list'),
    path('vendor-payments/create/', views.create_vendor_payment, name='create_vendor_payment'),
    path('vendor-payments/approve/<int:pk>/', views.approve_vendor_payment, name='approve_vendor_payment'),
    path('payroll/', views.payroll_summary, name='payroll_summary'),
]
# URLs updated for purchase export